# Generated by Django 6.0.1 on 2026-01-22 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReputationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("change", models.FloatField()),
                ("reason", models.CharField(max_length=255)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_logs",
                        to="contributors.contributor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
